# Generated by Django 3.1.2 on 2021-01-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='original_url',
            new_name='long_url',
        ),
    ]
