# Generated by Django 3.1.2 on 2021-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0004_auto_20210113_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(max_length=700),
        ),
    ]
